### ISSUE TITLE
The PUSH is not being send by the module

### ISSUE THREAD

**Issue by MattCorte** [mrDoctorWho/ejabberd_mod_gcm#11]
Hello Doctor, I'm trying to use your mod_gcm (and understand how it works) on Ejabberd 16.03, but i have a problem.
For start..i  have added the mod_gcm.erl in the ejabberd/src dir and also the following in the ejabberd.yml file under the MODULES section
`mod_gcm:
   gcm_api_key: gcm_api_key
`
where the last gcm_api_key is a global variable containing my API KEY (private, based on my Android App).
After the ejabberd reboot seems ok, the log return a row: mod_gcm:start:159 mod_gcm Has start successfully!.
So, as next step i've added to my Android XMPPManager Class the method to send the set iq stanza with the server and token (sender gcm registration id) info. This is what i've sent (Android Studio log):
`<iq to='myserveraddr' id='dPqJJ-10' type='set'><register xmlns='https://android.googleapis.com/gcm'><key>f6Es9KFADRQ:APA92bGovzSlDsM3v0vmEaOTbQduDIj2pZbd8TRA_J7fLP_lH1CrhlG-sI62Iyi2L6sNXK0HZAIdFs5F7AUobIVCf4ZVfXxE0tDZek1TNwardz4aa1PbsE8gLzFEx5IQ1MQgdNAymQg-</key></register></iq>`
The response seems ok (Android Studio log), no error:
`<iq from='myserveraddr' to='1@myserveraddr/f6Es9KFADRQ' id='dPqJJ-10' type='result'/>`
(f6Es9KFADRQ is the device name and is ok)

In the Ejabberd log now i can see a row that say that a new user has been registered (1@myserveraddr)... OK!

Done the above "registration" for both the user n.1 and n.2 (with success) i've tried to send a message from user n.1 to the offline user n.2, but on the Ejabberd log i've found the following error:
`mod_gcm:message:89 FORMAT ERROR: "Offline message ~s [{jid,<<"1">>,<<"myserveraddr">>,<<"f6Es9KFADRQ">>,<<"1">>,<<"myserveraddr">>,<<"f6Es9KFADRQ">>}]`

the offline message was not sent.. what can be the problem?

-- EDIT --

Changing the mod_gcm.erl INFO_MSG log parameter from [From] to [To]:
`?INFO_MSG("Offline message ~s", [To]),`
i noticed that return the same jid info of the sender (1, myserveraddr, f6Es9KFADRQ), it should be "2"?.. but i don't know how to set it

**Comment by MattCorte** [comment]
Please can you give me support? I really need to find a solution! Thank you.

**Comment by joanlopez** [comment]
Hi @MattCorte,

I'm not sure about what is happening but I'm really sure that the problem is not the error you've shared:

```
mod_gcm:message:89 FORMAT ERROR: "Offline message ~s [{jid,<<"1">>,<<"myserveraddr">>,<<"f6Es9KFADRQ">>,<<"1">>,<<"myserveraddr">>,<<"f6Es9KFADRQ">>}]
```

This is a "type" problem. You can change the variable type on the print command:

`~s` by `~n`

and it'll work

**Comment by mrDoctorWho** [comment]
Hi @MattCorte,

I'm terribly sorry, but I was unable to answer when you created the issue and then your email just got lost. 

Actually, @joanlopez is right, the error you've shown is not a fatal error. It won't stop the module from sending the PUSH.

> file under the MODULES section
> mod_gcm: gcm_api_key: gcm_api_key 

This looks like a first error. The module requires a global option. This actually isn't right and I'm gonna fix it someday.

**Comment by MattCorte** [comment]
Thank you for the reply @joanlopez ! it's strange because is the only "mod_gcm" line on my log after the message sending, but if i try to restart ejabberd i got an @ejabberd_config error:
`@ejabberd_config:validate_opts:823 unknown option 'gcm_api_key' will ne likely ignored`
but after that i got:
`@mod_gcm:start:159 mod_gcm Has started successfully!`
Maybe a wrong global variable declaration? The gcm_api_key is under the S2S GLOBAL OPTIONS sections of the ejabberd.yml config file, and contain the cloud messaging server key (found on the firebase console).

**Comment by MattCorte** [comment]
Hi @mrDoctorWho sorry i've not well understood, is there any method to set a correct global option for the module? Or not?

**Comment by mrDoctorWho** [comment]
@MattCorte you seem to have defined all correctly now.

Actually, I'm not sure if the module works now. There might have been a change in Google Cloud Messaging API. @joanlopez told me something about that before.

I think I will have to check on it, say, tomorrow.

If you are in rush, you can check out @joanlopez's [fork](https://github.com/joanlopez/ejabberd-mod-gcm) of my module.

**Comment by MattCorte** [comment]
Ok @mrDoctorWho please let me know asap! And about the @joanlopez fork of the module, i've saw that is a variant to use MySQL instead Mnesia, but i've just to replace the module or there are other things to set? @joanlopez i've not found any changes on the readme file.

**Comment by mrDoctorWho** [comment]
@MattCorte of course I would let you know!

Sorry, I'm not aware of @joanlopez module much, but I think you only need to go through mysql setup in ejabberd.

**Comment by joanlopez** [comment]
Hi @mrDoctorWho, @MattCorte

Yes, the problem may be that Google changed the Push API.

I'm not sure If using my plugin is a good recommendation. It has some other features that hasn't been tested yet. It's not reliable.

IMO, a better choice could be try to adapt the @mrDoctorWho module to the API's changes. You can see a summary in this commit:

https://github.com/joanlopez/ejabberd-mod-gcm/commit/85740e1526780aa35be5c79ef8dccf072c6a07f1

Just to mention it:
- New `NS_GCM` URL (I kept the old one, but you can replace it)
- New `CONTENT_TYPE` (now should be: "application/json")
- The parameters should be sent with another structure (see the code on the commit)

I think that with these three changes the plugin should work.

Thanks!

**Comment by mrDoctorWho** [comment]
Okay, finally I checked it.

It seems that the old module works just fine. The old NS_GCM url, old CONTENT_TYPE and all. And I don't know where the problem can be.

I'll add more debugging to the module and clean it up a bit (it was my first experience with Erlang, so...) and let you know.

**Comment by mrDoctorWho** [comment]
Dear watchers, can anyone confirm my words? Or nobody reads their email?

**Comment by MattCorte** [comment]
I will make a test in minutes, let you know!

**Comment by MattCorte** [comment]
@mrDoctorWho what about the way to define the global variable with the API KEY and pass it to the module? It seemed to understand that my way was not good.

**Comment by mrDoctorWho** [comment]
@MattCorte currently the module requires the gcm_api_key option is to be global. But I'm working now on making it local to the module section.

**Comment by MattCorte** [comment]
@mrDoctorWho i'm trying to edit the erl file of the module, but i notice that even if i restart ejabberd after have saved the changes return always the same log messages, seems is not keeping the changes.. i have to empty some module's cache?

**Comment by mrDoctorWho** [comment]
@MattCorte first, please update the module from git. Second, enable debug logging in ejabberd (set loglevel to 5). Third, move the gcm_api_key option from global section to the mod_gcm section as it said in README. Then compile the module and install it. Don't forget to compile and install the module after any change.

After the steps above completed you can now try to send the PUSH. The module will report what it's doing on each step.

**Comment by MattCorte** [comment]
Done, now the messages produced on the log are:
`mod_gcm: got offline message.`
`mod_gcm: updating last_seen for user 1@mydomain.com`

**Comment by mrDoctorWho** [comment]
Did you even try to send an offline message?

**Comment by MattCorte** [comment]
Yes of course, the above log is generated when i try to send a message from user n. 1 to offline user n. 2 (as wrote on my first post), on the Ejabberd admin page i can see the offline messages listed on the queue, and when the user n. 2 go online all the messages are received, so everything works as expected (except the module).  Anyway i'm not receiving anymore the format error message (i think because now the API KEY is correctly took), but seems that the case type of "normal" portion of the code is not taken in consideration, maybe because the case is another.. Today i try to add some info log to better understand what is happened.
-- EDIT --
Added a debug for the type, return "chat"
`"normal" -> ok;`
`_ ->`
Is handled by the _ -> case?

**Comment by mrDoctorWho** [comment]
@MattCorte do users have subscription both?

**Comment by MattCorte** [comment]
Yes, the users are both registered, but i have only saw the registration row on the log as evidence, there is a way to check which users are registered on mnesia?
Here you can see my current mod_gcm.erl file and the Ejabberd log generated by my last try:
[https://codepad.co/snippet/xHtQB7Rh](https://codepad.co/snippet/xHtQB7Rh)
[https://codepad.co/snippet/ZpOKauCg](https://codepad.co/snippet/ZpOKauCg)

**Comment by mrDoctorWho** [comment]
@MattCorte please dont edit your comments. If you want to add something, then write a new comment. I don't get email notifications about your editions. 

I don't ask if they're registered, I ask if their subscription is _both_.

I believe users are registered, but if you'd like to check, then run the following code in the ejabberd console (ejabberdctl debug):

``` erlang
mnesia:dirty_read(gcm_users, {<<"user">>, <<"host">>}).
```

This will show you the token of the username and host pair you provide.

**Comment by MattCorte** [comment]
Ok sorry for the edit, the mnesia:dirty_read does not return anything.

**Comment by MattCorte** [comment]
What you mean with subscription?  In which part of the procedure i must expect to do it?

**Comment by MattCorte** [comment]
@joanlopez tried also the edits suggested by you, same result, but i'm not sure if i have correctly done your edits.. if you want you can check the erl file with the changes on the link on the message above.

**Comment by mrDoctorWho** [comment]
@MattCorte your users should be able to receive presences of each other, that's what subscription is in jabber.

**Comment by MattCorte** [comment]
@mrDoctorWho it does, i can send and receive messages from both the users, i've took a log of the presence sending: [https://codepad.co/snippet/ByLEXlJr](https://codepad.co/snippet/ByLEXlJr) , please see rows from 09:12:49.890.
p.s The firsts link i posted was not working, now i've fixed them, you saw them? I really appreciate your help! Would be great if i can use your module!

**Comment by mrDoctorWho** [comment]
@MattCorte it has nothing to do with messages. You don't have to have subscription to send a message to someone else. Except your server has some limits for doing so.

Please check out this version of the module: https://gist.github.com/mrDoctorWho/01baf06dd994b62bc992300a6900742f . I've added more logging.

**Comment by MattCorte** [comment]
`2016-09-02 10:06:38.216 [debug] <0.11494.0>@mod_gcm:message:87 mod_gcm: got offline message`

`2016-09-02 10:06:38.216 [error] <0.11494.0>@mod_gcm:message:126 mod_gcm: 2@mydomain.com doesn't seem to have subscription both with 1@mydomain.com`
Understood. Now i search a way to do this subscription.. it's my first experience with Ejabberd and XMPP in general, so i appreciate if you have any suggestion. Thank you.

**Comment by mrDoctorWho** [comment]
@MattCorte what client do you use?

**Comment by MattCorte** [comment]
@mrDoctorWho Smack 4.1 for Android, [this one](https://github.com/igniterealtime/Smack)

**Comment by mrDoctorWho** [comment]
@MattCorte as far as I can see, this is not a client, but a client's library. If you're going to write a client of your own, then you need to consult with the XMPP Standards. Check out [this](https://xmpp.org/rfcs/rfc3921.html#sub) part which describes how to manage subscriptions.

**Comment by MattCorte** [comment]
Thank you @mrDoctorWho i will let you know if there are any changes on the log.

**Comment by MattCorte** [comment]
`2016-09-02 15:58:57.045 [debug] <0.14619.0>@mod_gcm:message:92 mod_gcm: got offline message`
`2016-09-02 15:58:57.045 [debug] <0.14619.0>@mod_gcm:message:120 mod_gcm: sending the message to GCM for user 2@mydomain.com`
`2016-09-02 15:58:57.283 [debug] <0.14619.0>@mod_gcm:send:82 mod_gcm: the message was sent`

@mrDoctorWho now it works! With Smack you can also manage the subscription requests. now i'm able to send GCM notification to the offline user. But i have a question. What if the user 1 write for the absolute first time to the user 2 while is offline? I mean, the user 1 take the contact of user 2 (that never had a contact with him) and send the first message, but the user 2 in that moment is offline. I've tried this scenario and on the Ejabberd log i got the "message sent" confirmation, but the offline message was never received by the user 2.

**Comment by mrDoctorWho** [comment]
@MattCorte I don't quite get what you mean. What do you mean by "never had contact". Is this about no both subscription or what?

**Comment by MattCorte** [comment]
Yes, i think no both subscription, because the user 2 is the first time that receive a message from user 1, but in that moment is offline, so user 2 have no sent subscription..

**Comment by mrDoctorWho** [comment]
@MattCorte I don't think this is a good idea, because of possible spams. But if you want, you can remove subscription check from the module.

**Comment by MattCorte** [comment]
Is possibile enable the subscription check after the first messages exchange? In this way an offline user can receive the gcm notification of the first message sent by another user. I think is a common scenario for a chat application. Hope i explained myself!

**Comment by mrDoctorWho** [comment]
@MattCorte Yes, I think this is possible. But we are talking about absolutely different module.
