### ISSUE TITLE
ejabberd 17.04 Support - Hook offline_message_hook crashed when running mod_gcm:message

### ISSUE THREAD

**Issue by pravino** [mrDoctorWho/ejabberd_mod_gcm#15]
2017-05-08 09:50:13.938 [error] <0.484.0>@ejabberd_hooks:safe_apply:383 Hook offline_message_hook crashed when running mod_gcm:message/1:
** Reason = {error,undef,[{mod_gcm,message,[],[{bounce,{message,<<>>,normal,<<"en">>,{jid,<<"cr3397">>,<<"kripter.io">>,<<"mobile">>,<<"cr3397">>,<<"kripter.io">>,<<"mobile">>},{jid,<<"dz9199">>,<<"kripter.io">>,<<>>,<<"dz9199">>,<<"kripter.io">>,<<>>},[],[],undefined,[{xmlel,<<"paused">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {0,0,0,0,0,65535,28806,20552}}}}]},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_sm,route,[{file,"src/ejabberd_sm.erl"},{line,138}],1},{ejabberd_local,route,[{file,"src/ejabberd_local.erl"},{line,116}],1},{ejabberd_router,do_route,[{file,"src/ejabberd_router.erl"},{line,346}],1},{ejabberd_router,route,[{file,"src/ejabberd_router.erl"},{line,87}],1},{ejabberd_c2s,check_privacy_then_route,[{file,"src/ejabberd_c2s.erl"},{line,770}],2}]}

**Comment by mrDoctorWho** [comment]
Module doesn't work with ejabberd versions after 16.09

**Comment by pravino** [comment]
Thanks for the reply, any new plugin on the way for news versions ???

**Comment by mrDoctorWho** [comment]
Not that I'm aware of.

**Comment by pravino** [comment]
:) r u planning on developing a fix for this

**Comment by mrDoctorWho** [comment]
Yeah, but I'm not a big fan of erlang and I don't have much time beside my main job.

I can't promise I'll do that soon, but one day I will push a fix just like it was when we updated from ejabberd 14 to ejabberd 15.

**Comment by mrDoctorWho** [comment]
Closing as not a real issue.
