### ISSUE TITLE
Unable to use it

### ISSUE THREAD

**Issue by naeems** [mrDoctorWho/ejabberd_mod_gcm#3]
Hi Doctor,

I have tried using this  module and followed your mentioned steps. I am using Android and my device is nexus 5 with 5.1 OS.

I have declared module in yml like following

 mod_gcm:
   gcm_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxx"

and copied .beam file in ebin directory. I am using 15.04 version of Ejabberd. 

How I tested:
After login I sent a packet with mentioned format. But and then put the A party on offline mode. Then I tried sending messages from Party B and no push message was received. Can you please help me getting fixed this issue thanks.

**Comment by mrDoctorWho** [comment]
Hello @naeems,

Did you add _mod_gcm_ to the modules list? If so, try to enable debug logging in ejabberd and try the steps you mentioned above again. Then look for "mod_gcm" messages the ejabberd log file.

**Comment by naeems** [comment]
Hi Doctor,

Thanks for your quick response and your great effort by developing this module. I am new to erlang so was not able to setup properly. I have retried again and its went very well. Its now sending push notifications. 

I have just confusion:
I have declared gcm_api_key in two places one is in module declaration list and other one is under begun level. Now please tell me where exact this is needed. I think it should be under module list right?

Once more question have you developed iOS push notification module too? Or can you help me developing iOS push module. I am interested in iOS push module too.

Thanks again for you kind effort and hard work.

Naeem

**Comment by mrDoctorWho** [comment]
@naeems,

_mod_gcm_ requires a global option for the api key. So the one in the modules list is not needed.

As for iOS, I'd like to add support for iOS push messages to this module, but I'm unable to test it.

If you like, I can help you to develop it or I can do it myself, but with your help. Although it shouldn't be hard. The code is almost ready, you just need to replace the code working with Google APIs by code working with Apple Push.

Anyways, I think GitHub is not a right place to discuss such things, so I suggest you to add my JID or something so we could discuss it well.

~~Jabber ID: mrdoctorwho@helldev.net~~
GTalk/Hangouts/Email: mrdoctorwho@gmail.com

If you have no more questions, please, close the issue.

**Comment by naeems** [comment]
Thanks for your support and help Doctor.
