### ISSUE TITLE
Instead of sending use it as a mechanism for connection

### ISSUE THREAD

**Issue by bangarharshit** [mrDoctorWho/ejabberd_mod_gcm#4]
Hi, It's a great plugin especially for mobile apps where chances of your service getting killed is very high. It's not useful for offline messages since GCM is based on XMPP and will itself be offline. GCM have even more problems with a very high ping time. 

I wanted to see if it can be modified to signal a new message and get the xmpp reconnected. Sending offline messages through GCM have few issue since there is no roster, no jingle support and if used as signaling it will be great.

**Comment by mrDoctorWho** [comment]
Hey!

As far as I know, GCM is not all about XMPP. For example, this module communicates with the GCM Servers using JSON. Anyways, that does not matter. 

Let's talk about signalling. I didn't quite understand what do you mean by signalling. Signal when and how (well, it's obvious it's gonna be over GCM), why do you want a client to reconnect?

**Comment by bangarharshit** [comment]
I checked that mod_push is trying to do the same to use GCM as signaling. Stream resumption is used to reconnect the client if the connection is found to be dead. Unfortunately it is still not available with ejabberd master and will take atleast few more months.

**Comment by mrDoctorWho** [comment]
So is that what you want — send client a signal that the connection hanged? But doesn't the client has that ability? Sorry, I'm not really aware of this part.

**Comment by bangarharshit** [comment]
I don't know what is xep-0357 used for. It states that it is useful for offline messages but I doubt if it is useful. From XEP-0357 page- Typically, these notifications are delivered to a user's mobile device, displaying a notice that can trigger opening an XMPP client to continue a conversation or answer a Jingle session request.

Server can send client the pings after some time but there is no way to make it online.

Sending offline message via GCM is great but XMPP have way too many side effects like ack, jingle for which you need to wake up client. You send the call data - jingle via GCM but if it is just message then no point. You need to start service to pick up the call and you will get the same message again since it was never acknowledged to server (XEP-198). Again GCM is one way connection and you have to open connection in any case to continue conversation. So why not just wakeup the client and let it handle everything. Even better with we can do stream resumption. 

I am no XMPP expert and still trying to understand why is it like that  and what is the use of 357  - https://github.com/royneary/mod_push/issues/4

Let me know if there are any issues or flaws in my understanding.

Thanks.

**Comment by mrDoctorWho** [comment]
As I can see @royneary already explained it well. I can only point out that XEP-0353 allows you to send stuff other than just messages. I believe (if you want) you can change the mentioned above mod_push to work in the way you want.

If you have no more questions, please, close the issue. Thanks.

**Comment by bangarharshit** [comment]
Thanks.  Closing the issue.
