### ISSUE TITLE
Will this module work for MUC?

### ISSUE THREAD

**Issue by kjakub** [mrDoctorWho/ejabberd_mod_gcm#7]

**Comment by kjakub** [comment]
offline_message_hook will this hook called also for MUC ?

**Comment by mrDoctorWho** [comment]
Hello @kjakub,

No, offline_message_hook is not being called on groupchat messages.

**Comment by kjakub** [comment]
@mrDoctorWho thanks for the info, do you know if there is another module support MUC push ?

**Comment by mrDoctorWho** [comment]
@kjakub I can't know for sure, but I believe [mod_push](https://github.com/royneary/mod_push/) will suit your needs

**Comment by joanlopez** [comment]
@kjakub Some months ago I made a fork from this repository in order to avoid MySQL databases (thanks to @mrDoctorWho). My fork is already working with MUC messages. However, I didn't make a good abstraction, so now it only works with MySQL..

Offer the possibility of using both is in my mind, but my module needs a refactor for this purpose.

PD: Sorry, I was very noob with Erlang (my first code lines in this language). Luckily, I'm learning a lot!

**Comment by kjakub** [comment]
@joanlopez ej, pretty nice if that works. Which version of ejabbered you are running ? I would like to try where is the fork ?

**Comment by joanlopez** [comment]
From an _ejabberd status_ command:

> ejabberd 16.03.92 is running in that node

**Comment by mrDoctorWho** [comment]
Hey @joanlopez, you didn't tell me you've done the MUCs

By the way, there's no actual way to get the MUC messages while user is offline (we actually have no idea which MUCs should be handled), so how'd you done this?

Edit: I checked out your repository and it seems your clients' send the list of groupchats to receive PUSHes from. Here we are talking about mod_gcm, but your fork of this module doesn't have such feature, I found it only in the apns module.

**Comment by mrDoctorWho** [comment]
@kjakub the fork is over there https://github.com/joanlopez/ejabberd-mod-apns but for APNS, not GCM.

**Comment by kjakub** [comment]
@mrDoctorWho thanks, well i need GCM, so i guess its time to start with Erlang and see how it goes, but thank you very much and @joanlopez for useful hints

**Comment by joanlopez** [comment]
@kjakub @mrDoctorWho I have a version with the muc messages hook also. I will upload both modules soon with some improvements, but these days i'm very busy.. Sorry :(

**Comment by kjakub** [comment]
@joanlopez that would be great! Let me know, plz!
